### ISSUE TITLE
error occured when build the source code

### ISSUE THREAD

**Issue by ITBeyond1230** [tatsy/educnn#1]
when I build the code ,error occured as below:
""""""
CMake Error at CMakeLists.txt:10 (find_package):
  By not providing "FindEigen3.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "Eigen3", but
  CMake did not find one.

  Could not find a package configuration file provided by "Eigen3" with any
  of the following names:

    Eigen3Config.cmake
    eigen3-config.cmake

  Add the installation prefix of "Eigen3" to CMAKE_PREFIX_PATH or set
  "Eigen3_DIR" to a directory containing one of the above files.  If "Eigen3"
  provides a separate development package or SDK, be sure it has been
  installed.

-- Configuring incomplete, errors occurred!
See also "/root/workspace/educnn/build/CMakeFiles/CMakeOutput.log".
"""
I don't konw how to do next .

**Comment by tatsy** [comment]
Hi @lisuichan,

Thanks for your interest to my code and I understand your problem.
However, that is not the problem of my code but because of your Eigen3 installation.
This is rather out of scope of issue tracking but I can help you to some extent if you provide further information about your environment (OS, compiler and so forth).

**Comment by tatsy** [comment]
Now, I added some sorts of codes to find Eigen3 semi-automatically.
Can you re-download and check that out, please?

If it does not work for you, please check "EIGEN3_ROOT" variable of CMake.

Cheers!

**Comment by ITBeyond1230** [comment]
Hi @tatsy ,
  My OS  is linux CentOS, I never install the Eigen3 before, and I  built the source code just follow your build instructions , that is ,
""""""""""""
# Setup Eigen:
# (The version here is 3.2.7, but you can specify any versions higher than 3.0.0)
$ wget -O eigen-3.2.7.zip http://bitbucket.org/eigen/eigen/get/3.2.7.zip
$ unzip -qq eigen-3.2.7.zip -d $YOUR_EIGEN_DIR

# Build educnn
$ git clone https://github.com/tatsy/educnn.git
$ mkdir build && cd build
$ cmake -D EIGEN3_INCLUDE_DIR=$YOUR_EIGEN_DIR ..
"""
And my $YOUR_EIGEN_DIR  is  /root/workspace/eigen;
At last ,some error occured  just I have reported.

**Comment by ITBeyond1230** [comment]
OK, I will re-download  the code and try to build it again! Thanks ! @tatsy

**Comment by tatsy** [comment]
Oh, I am sorry but I misunderstand the problem. Maybe this is because the unnecessary use of "find_package".

Actually, it should be OK that just commenting-out the "find_package" line (in the previous version).
In the current version, it would also work properly by specifying `EIGEN3_ROOT` as `/root/workspace/eigen`, so please try.

**Comment by ITBeyond1230** [comment]
Hi @tatsy , I have just re-download your code and re-build it ,and it seems successfully and I got some messages as follow,
"""
[root@lsc build]# cmake -D EIGEN3_INCLUDE_DIR=/root/workspace/eigen ..
-- Eigen3 found: /root/workspace/eigen
-- Configuring done
-- Generating done
-- Build files have been written to: /root/workspace/educnn/build
"""
But some errors occured when I make , 
""""
[root@lsc build]# make
[ 50%] Building CXX object sources/CMakeFiles/test_lecun.dir/test_lecun.cpp.o
c++: fatal error: no input files
compilation terminated.
/bin/sh: -fopenmp: command not found
make[2]: *** [sources/CMakeFiles/test_lecun.dir/test_lecun.cpp.o] Error 127
make[1]: *** [sources/CMakeFiles/test_lecun.dir/all] Error 2
make: *** [all] Error 2
""""
 I don't konw what's wrong now!

**Comment by tatsy** [comment]
I am not sure about CentOS but that is the problem of OpenMP (as the error message indicates).
I added an option to disable OpenMP to CMake script, so please re-doanload the code and run,

```shell
cmake -D EIGEN3_ROOT $YOUR_EIGEN_DIR -D WITH_OPENMP=OFF ..
```

**Comment by ITBeyond1230** [comment]
Thanks @tatsy  !
